Learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import courses,users
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('users.urls', namespace='users')),
    path("courses/", include('courses.urls',namespace='courses'))
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .import views
app_name ='courses'

urlpatterns = [
    ## Instructor Course Routes
    path('add/',views.CourseAdd.as_view(),name='course_add'),
    path("all/",views.CourseAll .as_view(), name="course_all"),
    path("view/<int:pk>/",views.CourseSingle.as_view(), name="course_view"),
    path("edit/<int:pk>/",views.CourseUpdate.as_view(), name="course_update"),
    path("delete/<int:pk>/",views.CourseRemove.as_view(), name="course_remove"),
    path("delete/topic/<int:pk>/",views.TopicRemove.as_view(), name="topic_remove"),

    ## Topic Routes
    path("topic/add/",views.TopicAdd.as_view(), name="topic_add"),
    path("topic/all/",views.TopicAll.as_view(), name="topic_all"),
    path("topic/view/<int:pk>/",views.TopicSingle.as_view(), name="topic_view"),
    path("topic/edit/<int:pk>/",views.TopicUpdate.as_view(), name="topic_update"),

    #StudentCourses/Topics
    path("student/all/",views.StudentCourses.as_view(), name="student_courses"),
    path("student/view/<int:pk>/",views.StudentCoursesingle.as_view(), name="student_course_single"),
    path("student/topics/",views.StudentTopics.as_view(), name="student_topics"),
    path("student/topic/view/<int:pk>/",views.StudentTopicsingle.as_view(), name="student_topic_single"),

    #Instructor Assignment/Answer
    path("instructor/assignment/add/",views.CreateAssignment.as_view(), name="assignment_add"),
    path("instructor/assignment/<int:pk>/edit/",views.UpdateAssignment.as_view(), name="assignment_update"),
    path("instrutor/assignment/<int:pk>/remove/",views.AssignmentRemove.as_view(), name="assignment_remove"),
    path("instructor/assignment/all/",views.AllAssignment.as_view(), name="assignment_all"),
    path("instructor/answer/<int:pk>/",views.ViewAnswer.as_view(), name="view_answer"),

    #studentAssignment/Answer
    path("student/assignment/all/",views.AllStudentAssignment.as_view(), name="student_assignment_all"),
    path("student/answer/<int:pk>/",views.StudentAnswer.as_view(), name="student_answer")
]

users/urls.py
from django.urls import path
from .import views



app_name = 'users'

urlpatterns = [
    path("instructor/sign-up/", views.Register.as_view(), name="instructor_register"),
    path("instructor/sign-in/", views.Login.as_view(), name="instructor_login"),
    path("instructor/dashboard/",views.Dashboard.as_view(), name="instructor_dashboard"),
    path("", views.Home.as_view(), name="index"),

    #Students
    path("student/sign-up/", views.StudentRegister.as_view(), name="student_register"),
    path("student/sign-in/", views.StudentLogin.as_view(), name="student_login"),
    path("student/dashboard/",views.StudentDashboard.as_view(), name="student_dashboard"),
    path("profile/<int:pk>/",views.Instructor_Profile.as_view(), name="instructor_profile"),
    path("student/profile/<int:pk>/",views.Student_Profile.as_view(), name="student_profile"),
    path("logout/",views.Logout.as_view(), name="logout"),
    path("logout/student/",views.Student_Logout.as_view(), name="student_logout")
]

templates/users/instructor/dashboard/index.html
{% extends 'users/instructor/layout.html' %}


{% block content %}

         
         
 <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="{% url 'courses:course_add' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"> &plus; Add Course</a>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Courses</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{incourse}}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
              
            </div>

             <div class="col-xl-6 col-md-6 mb-4">
              <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Topics</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{intopic}}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-folder fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>

          <!-- Content Row -->
        <div class="row">
              <!-- Approach -->
            <div class='col-lg-12'>
            <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Recent Courses</h6>
            </div>
            <div class="card-body">
               <table class="table table-striped">
                <thead>
                    <tr>
                    <th scope="col">Course-Code</th>
                    <th scope="col">Course-Name</th>
                    <th scope="col">File</th>
                     <th scope="col">Level/Levels</th>
                    <th scope="col">Author</th>
                    <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                {% for course in courses  %}
                    <tr>
                    <th scope="row">{{course.course_code}}</th>
                    <td>{{course.course_name}}</td>
                    <td>(<a href="{{course.file.url}}" class="">{{course.file}} <i class="fas fa-download"></i></a>)</td>
                    <td>{{course.level|capfirst}} / {{course.levels | capfirst}}</td>
                     <td>{{course.instructor.first_name}}-{{course.instructor.last_name}}</td>
                     <td>{{course.created}}</td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
            </div>
              <span class="text-right mr-3 mb-2">
                  <a href="{% url 'courses:course_all' %}" class="btn btn-primary">All Courses &rarr;</a>
              </span>
            </div>
            </div>


            <div class='col-lg-12'>
            <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Recent Topic</h6>
            </div>
            <div class="card-body">
               <table class="table table-striped">
                <thead>
                    <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Course</th>
                    <th scope="col">File</th>
                     <th scope="col">Levels</th>
                    <th scope="col">Author</th>
                    <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                {% for topic in topics  %}
                    <tr>
                    <th scope="row">{{topic.title}}</th>
                    <td>{{topic.course}}</td>
                    <td>(<a href="{{topic.file.url}}" class="">{{topic.file}} <i class="fas fa-download"></i></a>)</td>
                    <td>{{topic.levels | capfirst}}</td>
                     <td>{{topic.instructor.first_name}}-{{topic.instructor.last_name}}</td>
                     <td>{{topic.created}}</td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
            </div>
              <span class="text-right mr-3 mb-2">
                  <a href="{% url 'courses:topic_all' %}" class="btn btn-primary">All Topic &rarr;</a>
              </span>
            </div>
            </div>
        </div>
        </div>
     

      

{% endblock content %}

templates/users/instructor/dashboard/profile.html
{% extends 'users/instructor/layout.html' %}


{% block content %}

    <div class="row mt-4 mb-2">
      <div class="col-lg-6 shadow offset-lg-3 p-4">
        <form method='POST'>
          {{form.as_p}}
          <button class="btn btn-info btn-block">Update</button>
        </form>
      </div>
    </div>
          
     

      

{% endblock content %}