Learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import courses,users
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('users.urls', namespace='users')),
    path("courses/", include('courses.urls',namespace='courses'))
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .import views
app_name ='courses'

urlpatterns = [
    ## Instructor Course Routes
    path('add/',views.CourseAdd.as_view(),name='course_add'),
    path("all/",views.CourseAll .as_view(), name="course_all"),
    path("view/<int:pk>/",views.CourseSingle.as_view(), name="course_view"),
    path("edit/<int:pk>/",views.CourseUpdate.as_view(), name="course_update"),
    path("delete/<int:pk>/",views.CourseRemove.as_view(), name="course_remove"),
    path("delete/topic/<int:pk>/",views.TopicRemove.as_view(), name="topic_remove"),

    ## Topic Routes
    path("topic/add/",views.TopicAdd.as_view(), name="topic_add"),
    path("topic/all/",views.TopicAll.as_view(), name="topic_all"),
    path("topic/view/<int:pk>/",views.TopicSingle.as_view(), name="topic_view"),
    path("topic/edit/<int:pk>/",views.TopicUpdate.as_view(), name="topic_update"),

    #StudentCourses/Topics
    path("student/all/",views.StudentCourses.as_view(), name="student_courses"),
    path("student/view/<int:pk>/",views.StudentCoursesingle.as_view(), name="student_course_single"),
    path("student/topics/",views.StudentTopics.as_view(), name="student_topics"),
    path("student/topic/view/<int:pk>/",views.StudentTopicsingle.as_view(), name="student_topic_single"),

    #Instructor Assignment/Answer
    path("instructor/assignment/add/",views.CreateAssignment.as_view(), name="assignment_add"),
    path("instructor/assignment/<int:pk>/edit/",views.UpdateAssignment.as_view(), name="assignment_update"),
    path("instrutor/assignment/<int:pk>/remove/",views.AssignmentRemove.as_view(), name="assignment_remove"),
    path("instructor/assignment/all/",views.AllAssignment.as_view(), name="assignment_all"),
    path("instructor/answer/<int:pk>/",views.ViewAnswer.as_view(), name="view_answer"),

    #studentAssignment/Answer
    path("student/assignment/all/",views.AllStudentAssignment.as_view(), name="student_assignment_all"),
    path("student/answer/<int:pk>/",views.StudentAnswer.as_view(), name="student_answer")
]

users/urls.py
from django.urls import path
from .import views



app_name = 'users'

urlpatterns = [
    path("instructor/sign-up/", views.Register.as_view(), name="instructor_register"),
    path("instructor/sign-in/", views.Login.as_view(), name="instructor_login"),
    path("instructor/dashboard/",views.Dashboard.as_view(), name="instructor_dashboard"),
    path("", views.Home.as_view(), name="index"),

    #Students
    path("student/sign-up/", views.StudentRegister.as_view(), name="student_register"),
    path("student/sign-in/", views.StudentLogin.as_view(), name="student_login"),
    path("student/dashboard/",views.StudentDashboard.as_view(), name="student_dashboard"),
    path("profile/<int:pk>/",views.Instructor_Profile.as_view(), name="instructor_profile"),
    path("student/profile/<int:pk>/",views.Student_Profile.as_view(), name="student_profile"),
    path("logout/",views.Logout.as_view(), name="logout"),
    path("logout/student/",views.Student_Logout.as_view(), name="student_logout")
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class UserManager(AbstractUser):
    choice = (('ND-I','ND-I'),('ND-II','ND-II'),('HND-I','HND-I'),('HND-II','HND-II'))
    result = (('easy','Lower-Credit'),('difficult','Upper-Credit'),('easy','Pass'),('difficult','Distinction'))
    is_teacher = models.BooleanField(null=True)
    is_student = models.BooleanField(null=True)
    mobile_number = models.CharField(max_length=13, null=True)
    office = models.CharField(max_length=50, null=True)
    level = models.CharField(max_length=8,choices=choice, null=True)
    prev_result = models.CharField(choices=result, max_length=20, null=True)
    image = models.ImageField()

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from .models import UserManager

class StaffRegForm (UserCreationForm):

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user','placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user','placeholder':'Confirm Password'}))
    username = forms.CharField(help_text="<p class='text-danger lead'>Maximum of 6 Characters, Minimum of 5</p>",widget=forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Instructors username','maxlength':'9','minlength':'7'}))
    is_teacher = forms.CharField(widget=forms.HiddenInput(attrs={'value':'1'}))
    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','email','username','password1','password2','mobile_number','office','image','is_teacher')
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'First Name'}),
            'last_name':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Last Name'}),
            'email':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'E-mail Address'}),
            'mobile_number':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':' Mobile Number'}),
            'office':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Office Address'}),
            'image':forms.ClearableFileInput(attrs={'class':'form-control'})

        }
        

class StaffLoginForm(AuthenticationForm):
    
    username = forms.CharField(help_text="<p class='text-danger lead'>Maximum of 6 Characters, Minimum of 5</p>",widget=forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Instructor username','maxlength':'9','minlength':'7'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'placeholder':'Valid Password '}))

    class Meta:
        model=get_user_model()
        fields = ('username','password')


class StudentRegForm (UserCreationForm):

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user','placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user','placeholder':'Confirm Password'}))
    is_student = forms.CharField(widget=forms.HiddenInput(attrs={'value':'1'}))
    username = forms.CharField(label='Matric Number',max_length=14, min_length=11, widget=forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Student Matric Number'}))
    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','email','username','password1','password2','prev_result','level','image','is_teacher')
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'First Name','required':'required'}),
            'last_name':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Last Name','required':'required'}),
            'email':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'E-mail Address','required':'required'}),
            #'username':forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Student username'}),
            'level':forms.Select(attrs={'class':'form-control','placeholder':'Level','required':'required'}),
            'prev_result':forms.Select(attrs={'class':'form-control','value':'Previous Result','required':'required'}),
            'image':forms.ClearableFileInput(attrs={'class':'form-control','required':'required'})

        }


class StudentLoginForm(AuthenticationForm):
    
    username = forms.CharField(help_text="<p class='text-danger lead'>Maximum of 14 Characters, Minimum of 11</p>",widget=forms.TextInput(attrs={'class':'form-control form-control-user','required':'required','placeholder':'Student Matric Number','maxlength':'14','minlength':'11'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'required':'required', 'placeholder':'Valid Password '}))
    # level = forms.ChoiceField(choices=UserManager.choice,  widget=forms.Select(attrs={'class':'form-control form-control-user'}))
    # prev_result = forms.ChoiceField(choices=UserManager.result,label='Current Grade',widget=forms.Select(attrs={'class':'form-control form-control-user'}))

    class Meta:
        model=get_user_model()
        fields = ('username','password')

   
class Instructor_Profile(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','username','email','mobile_number','image')

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'last_name':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'username':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'email':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'mobile_number':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'image':forms.ClearableFileInput(attrs={'class':'form-control form-control-user'}),
        }

class Student_Profile(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','username','email','mobile_number','image')

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'last_name':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'username':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'email':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'mobile_number':forms.TextInput(attrs={'class':'form-control form-control-user'}),
            'image':forms.ClearableFileInput(attrs={'class':'form-control form-control-user'}),
        }

users/views.py
from django.shortcuts import render,redirect    
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, View
from django.contrib.auth.views  import LoginView
from django.contrib.auth import get_user_model,logout
from courses.models import Course,Topic
from .forms import StaffRegForm, Student_Profile, StaffLoginForm, StudentRegForm, StudentRegForm, StudentLoginForm, Instructor_Profile
from django.db.models import Q

# Create your views here.
class Home (TemplateView):
    template_name = 'users/index/index.html'

class Register (CreateView):
    model = get_user_model()
    template_name = 'users/instructor/signup.html'
    form_class = StaffRegForm


    def get_success_url (self):
        url = reverse_lazy('users:instructor_login')
        return url
    

class Login (LoginView):
    template_name = 'users/instructor/login.html'
    form_class = StaffLoginForm

    def get_success_url(self):
        success_url = reverse_lazy('users:instructor_dashboard')
        return success_url


class Dashboard (TemplateView):
    template_name = 'users/instructor/dashboard/index.html'
    def get_context_data(self, **kwargs):
        # self.request.session['lect'] = get_user_model().objects.get(username=self.request.user)
        context = super().get_context_data(**kwargs)
        context["incourse"] = Course.objects.filter(instructor=self.request.user).count()
        context["intopic"] = Topic.objects.filter(instructor=self.request.user).count()
        context["courses"] = Course.objects.filter(instructor=self.request.user)[:5]
        context['topics'] = Topic.objects.filter(instructor=self.request.user)[:5]

        return context

class StudentRegister (CreateView):
    model = get_user_model()
    template_name = 'users/student/signup.html'
    form_class = StudentRegForm
    success_url = reverse_lazy('users:student_login')

class StudentLogin (LoginView):
    template_name = 'users/student/login.html'
    form_class = StudentLoginForm

    def get_success_url(self):
        # level = self.request.POST['level']
        # result = self.request.POST['prev_result']
        # self.request.session['level'] = level
        # self.request.session['result'] =result
        
        url = reverse_lazy('users:student_dashboard')
        return url

class StudentDashboard (TemplateView):
    template_name = 'users/student/dashboard/index.html'
    def get_context_data(self, **kwargs):
        # self.request.session['lect'] = get_user_model().objects.get(username=self.request.user)
        context = super().get_context_data(**kwargs)
        context["incourse"] = Course.objects.filter(level=self.request.user.level).count()
        context["intopic"] = Topic.objects.filter(Q(levels=self.request.user.prev_result) & Q(course__level=self.request.user.level)).count()
        context["courses"] = Course.objects.filter(level=self.request.user.level)[:5]
        context['topics'] = Topic.objects.filter(Q(levels=self.request.user.prev_result) | Q(course__level=self.request.user.level))[:5]
        # context['']

        return context

class Instructor_Profile(UpdateView):
    model = get_user_model()
    template_name = 'users/instructor/dashboard/profile.html'
    form_class = Instructor_Profile


class Student_Profile(UpdateView):
    model = get_user_model()
    template_name = 'users/student/dashboard/profile.html'
    form_class = Student_Profile

class Logout(View):
    def get (self,request):
        logout(self.request)
        return redirect('users:instructor_login', permanent=True)

class Student_Logout(View):
    def get (self,request):
        logout(self.request)
        return redirect('users:student_login', permanent=True)

templates/users/instructor/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Instructor Login</title>

  <!-- Custom fonts for this template-->
   <!-- Custom fonts for this template-->
  <link href=" {% static 'users/vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href=" {% static 'users/css/sb-admin-2.min.css' %} " rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form method='POST'>
                  {% csrf_token %}  
                    <div class="form-group">
                      {{form.username}}                    
                    </div>
                    <div class="form-group">
                      {{form.password}}                    
                    </div>
                  
                    <button class="btn btn-primary btn-user btn-block">
                      Login
                    </button>
                    </form>
                    <hr>
                  
                  <div class="text-center">
                    <a class="small" href="{% url 'users:instructor_register' %}">Create an Account!</a> <br>
                    <a class="small" href="{% url 'users:index' %}">Back Home</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

 <script src=" {% static 'users/vendor/jquery/jquery.min.js' %} "></script>
  <script src=" {% static 'users/vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

  <!-- Core plugin JavaScript-->
  <script src=" {% static 'users/vendor/jquery-easing/jquery.easing.min.js' %} "></script>

  <!-- Custom scripts for all pages-->
  <script src=" {% static 'users/js/sb-admin-2.min.js' %} "></script>

</body>

</html>

templates/users/instructor/navbar.html
   <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.first_name}}</span>
                <img class="img-profile rounded-circle" src="{{user.image.url}}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'users:instructor_profile' pk=user.id %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href='{% url 'users:logout' %}' >
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>

templates/users/instructor/sidebar.html
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-book"></i>
        </div>
        <div class="sidebar-brand-text mx-3">E-Learning </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'users:instructor_dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
       Learning
      </div>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'courses:course_all' %}" >
          <i style='font-size: 1.3em' class="fas text-light fa-book"></i>
          <span style='font-size: 1em'>Course</span>
        </a>
      </li>

       <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'courses:topic_all' %}" >
          <i style='font-size: 1.3em' class="fas text-light fa-file"></i>
          <span style='font-size: 1em'>Topics</span>
        </a>
      </li>

       <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'courses:assignment_all' %}" >
          <i style='font-size: 1.3em' class="fas text-light fa-archive"></i>
          <span style='font-size: 1em'>Assignment</span>
        </a>
      </li>


      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

templates/users/instructor/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Register</title>

  <!-- Custom fonts for this template-->
  <link href=" {% static 'users/vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href=" {% static 'users/css/sb-admin-2.min.css' %} " rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Instructor's Account Creation </h1>
              </div>
              <form class="user" method="POST" enctype="multipart/form-data">
              {{form.errors}}
                <div class="form-group row">
                {% csrf_token %}
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      {{form.first_name}}         
                  </div>
                  <div class="col-sm-6">
                    {{form.last_name}}
                  </div>
                </div>
                <div class="form-group">
                  {{form.email}} 
                </div>
                <div class="form-group">
                  {{form.username}} 
                </div>
                <div class="form-group">
                  {{form.mobile_number}} 
                </div>
                <div class="form-group">
                  {{form.office}} 
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                   {{form.password1}}                  
                </div>
                <div class="col-sm-6">
                   {{form.password2}}                  
                </div>
                </div>
                <div class="form-group">
                  {{form.image}} 
                </div>
                <div class="form-group">
                  {{form.is_teacher}} 
                </div>
                <button  class="btn btn-primary btn-user btn-block">
                  Register Account
                </button>
                <hr>
              
              </form>
              <hr>
              
              <div class="text-center">
                <a class="small" href="{% url 'users:instructor_login' %}">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

 <script src=" {% static 'users/vendor/jquery/jquery.min.js' %} "></script>
  <script src=" {% static 'users/vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

  <!-- Core plugin JavaScript-->
  <script src=" {% static 'users/vendor/jquery-easing/jquery.easing.min.js' %} "></script>

  <!-- Custom scripts for all pages-->
  <script src=" {% static 'users/js/sb-admin-2.min.js' %} "></script>
   {% block validation%}
    <script>
    /** const firstName = document.getElementById('id_first_name')    
      document.getElementById('id_first_name').addEventListener('input', function(){
        if (Number.parseInt(firstName.value) | firstName.value == 0){
          firstName.value = ''
        }
      })

      const lastName = document.getElementById('id_last_name')    
      document.getElementById('id_last_name').addEventListener('input', function(){
        if (Number.parseInt(lastName.value) | lastName.value == 0){
          lastName.value = ''
        }
      }) **/

    </script>
  {% endblock validation%}
</body>

</html>