Learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import courses,users
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('users.urls', namespace='users')),
    path("courses/", include('courses.urls',namespace='courses'))
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .import views
app_name ='courses'

urlpatterns = [
    ## Instructor Course Routes
    path('add/',views.CourseAdd.as_view(),name='course_add'),
    path("all/",views.CourseAll .as_view(), name="course_all"),
    path("view/<int:pk>/",views.CourseSingle.as_view(), name="course_view"),
    path("edit/<int:pk>/",views.CourseUpdate.as_view(), name="course_update"),
    path("delete/<int:pk>/",views.CourseRemove.as_view(), name="course_remove"),
    path("delete/topic/<int:pk>/",views.TopicRemove.as_view(), name="topic_remove"),

    ## Topic Routes
    path("topic/add/",views.TopicAdd.as_view(), name="topic_add"),
    path("topic/all/",views.TopicAll.as_view(), name="topic_all"),
    path("topic/view/<int:pk>/",views.TopicSingle.as_view(), name="topic_view"),
    path("topic/edit/<int:pk>/",views.TopicUpdate.as_view(), name="topic_update"),

    #StudentCourses/Topics
    path("student/all/",views.StudentCourses.as_view(), name="student_courses"),
    path("student/view/<int:pk>/",views.StudentCoursesingle.as_view(), name="student_course_single"),
    path("student/topics/",views.StudentTopics.as_view(), name="student_topics"),
    path("student/topic/view/<int:pk>/",views.StudentTopicsingle.as_view(), name="student_topic_single"),

    #Instructor Assignment/Answer
    path("instructor/assignment/add/",views.CreateAssignment.as_view(), name="assignment_add"),
    path("instructor/assignment/<int:pk>/edit/",views.UpdateAssignment.as_view(), name="assignment_update"),
    path("instrutor/assignment/<int:pk>/remove/",views.AssignmentRemove.as_view(), name="assignment_remove"),
    path("instructor/assignment/all/",views.AllAssignment.as_view(), name="assignment_all"),
    path("instructor/answer/<int:pk>/",views.ViewAnswer.as_view(), name="view_answer"),

    #studentAssignment/Answer
    path("student/assignment/all/",views.AllStudentAssignment.as_view(), name="student_assignment_all"),
    path("student/answer/<int:pk>/",views.StudentAnswer.as_view(), name="student_answer")
]

users/urls.py
from django.urls import path
from .import views



app_name = 'users'

urlpatterns = [
    path("instructor/sign-up/", views.Register.as_view(), name="instructor_register"),
    path("instructor/sign-in/", views.Login.as_view(), name="instructor_login"),
    path("instructor/dashboard/",views.Dashboard.as_view(), name="instructor_dashboard"),
    path("", views.Home.as_view(), name="index"),

    #Students
    path("student/sign-up/", views.StudentRegister.as_view(), name="student_register"),
    path("student/sign-in/", views.StudentLogin.as_view(), name="student_login"),
    path("student/dashboard/",views.StudentDashboard.as_view(), name="student_dashboard"),
    path("profile/<int:pk>/",views.Instructor_Profile.as_view(), name="instructor_profile"),
    path("student/profile/<int:pk>/",views.Student_Profile.as_view(), name="student_profile"),
    path("logout/",views.Logout.as_view(), name="logout"),
    path("logout/student/",views.Student_Logout.as_view(), name="student_logout")
]

templates/users/instructor/assignment/all.html
{% extends 'users/instructor/layout.html' %}
{% load humanize %}
{% block title %}
    All Assignments
{% endblock title %}

{% block content %}
    <section class="row">
        <div class="col-lg-12 mt-4">
            <span class="lead mb-3">All Assignment Added By You</span>
            <div class="card shadow mt-2 mb-4">
            <div class="card-header py-3">
            </div>
            <div class="card-body">
            {% if assignments %}
               <table class="table table-striped">
                <thead>
                    <tr>
                    
                    
                    <th scope='col'>Course</th>
                    <th scope="col">Level</th>
                     <th scope="col">Created</th>
                    <th scope="col">Author</th>
                    <th scope="col">Manage</th>
                    </tr>
                </thead>
                <tbody>
                {% for ass in assignments  %}
                    <tr>
                   
                    <td>{{ass.course}}</td>
                    <td>{{ass.level}}</td>
                    <td>{{ass.created | capfirst}}</td>
                     <td>{{ass.author}}</td>
                     <td> <a href="{% url 'courses:assignment_update' pk=ass.pk %}"><i class="fas fa-edit text-info"></i></a> &emsp; <a href="{% url 'courses:assignment_remove' pk=ass.id %}"><i class="fas fa-trash text-danger"></i></a>&emsp; <a href="{% url 'courses:view_answer' pk=ass.id %}" class="btn btn-sm btn-info">View Answers</a></td>
                     </tr>
                {% endfor %}
                </tbody>
                </table>
            {% else %}
                <p class="display-4 ext-center">No Assignments in the Database</p>
                <div class='text-center'>
                    <a href="{% url 'courses:assignment_add' %}" class="btn btn-info btn-block">Add An Assignment</a>
                </div>
            {% endif %}
            </div>
            </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/users/instructor/assignment/answer.html
{% extends 'users/instructor/layout.html' %}
{% load humanize %}
{% block title %}
    All Answers
{% endblock title %}

{% block content %}
    <section class="row">
        <div class="col-lg-12 mt-4">
            <span class="lead mb-3">All Answered Assignment</span>
            <div class="card shadow mt-2 mb-4">
            <div class="card-header py-3">
            </div>
            <div class="card-body">
            {% if asnswers %}
               <table class="table table-striped">
                <thead>
                    <tr>
                    
                    
                    <th scope='col'>Course</th>
                    <th scope="col">SubmittedBy</th>
                     <th scope="col">Date</th>
                    <th scope="col">File</th>
                    </tr>
                </thead>
                <tbody>
                {% for ans in answers  %}
                    <tr>
                   
                    <td>{{ans.course}}</td>
                    <td>{{ans.matric}}</td>
                    <td>{{ass.submitted | capfirst}}</td>
                     <td><a href="{% url '{{ans.answer.url}}' %}">Download File </a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
            {% else %}
                <p class="display-4 ext-center">No Answers in the Database</p>
                
            {% endif %}
            </div>
            </div>
            </div>
        </div>
    </section>
{% endblock content %}